---
title: "Oxford|Berlin Summer School on Open Research 2021"
---

Welcome to the 4th edition of the Oxford\|Berlin summer school on Open Research taking place online on 20 - 23 September 2021! It is a free course for early career researchers (post graduate students (MSc, PhD, and postdocs) who would like to learn more about how to make their research open, reliable, reproducible, and replicable. The course is organised by researchers from Reproducible Research Oxford, University of Oxford, and the QUEST Center for Transforming Biomedical Research, Berlin Institute of Health, in collaboration with Freie Universität Berlin and Charité University Hospital. The school is generously funded by the Berlin University Alliance. On this website you can find some useful information on our programme, video recordings of our lectures, and workshop materials. You can get in touch with the summer school organisers via email here: [summerschool_berlinoxford\@bihealth.de](mailto:summerschool_berlinoxford@bihealth.de){.email}

The four-day summer school consists of a series of lectures that cover the following topics:\
- Biases in research\
- Reproducibility\
- Best practices for sharing publications, data, and code\
- Meta-research\
- Ethical conduct of research

The lectures are complemented by a series of interactive workshops, which participants can choose from based on their needs (e.g. introduction to R and Python, reproducible workflows, version control in Git and Github, data management, and preregistration). You can find presentation slides and recordings, as well as workshop material in our [OSF repository](https://osf.io/8q59y/).
